/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PreviewDialog.java
 *
 * Created on 14.05.2009, 20:15:54
 */

package peripheral.designer.preview;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;
import javax.swing.BorderFactory;

/**
 *
 * @author Berni
 */
public class PreviewDialog extends javax.swing.JDialog {


    /** Creates new form PreviewDialog */
    public PreviewDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        previewPanel1 = new PreviewPanel(this);
        getContentPane().add(previewPanel1,java.awt.BorderLayout.CENTER);
        previewPanel1.setPreferredSize(new Dimension(400,300));
        initComponents();

        //add listener to be aware of cleaning up in case of closing window
        this.addWindowListener(new WindowListener () {

            public void windowOpened(WindowEvent e) {
            }
            public void windowClosing(WindowEvent e) {
                previewPanel1.flushResources();
            }
            public void windowClosed(WindowEvent e) {
            }
            public void windowIconified(WindowEvent e) {
            }
            public void windowDeiconified(WindowEvent e) {
            }
            public void windowActivated(WindowEvent e) {
            }
            public void windowDeactivated(WindowEvent e) {
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        southPanel = new javax.swing.JPanel();
        xLabel = new javax.swing.JLabel();
        xValueLabel = new javax.swing.JLabel();
        yLabel = new javax.swing.JLabel();
        yValueLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        xLabel.setText("X:");
        southPanel.add(xLabel);

        xValueLabel.setText("0");
        southPanel.add(xValueLabel);

        yLabel.setText("Y:");
        southPanel.add(yLabel);

        yValueLabel.setText("0");
        southPanel.add(yValueLabel);

        getContentPane().add(southPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setBackgroundImage(File sourceFile) {
        previewPanel1.setBackgroundImage(sourceFile);
    }

    public boolean isExtentionSupported(File sourceFile) {
        return previewPanel1.isImageFile(sourceFile);
    }

    public void setMouseCoords(int x, int y) {
        xValueLabel.setText(""+x);
        yValueLabel.setText(""+y);
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PreviewDialog dialog = new PreviewDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel southPanel;
    private javax.swing.JLabel xLabel;
    private javax.swing.JLabel xValueLabel;
    private javax.swing.JLabel yLabel;
    private javax.swing.JLabel yValueLabel;
    // End of variables declaration//GEN-END:variables

    private PreviewPanel previewPanel1;
}
