#!/bin/sh

cd tmp

CLASSPATH=".;lib/processing-1.0.3-essentials/lib/core.jar;lib/processing-1.0.3-essentials/libraries/opengl/library/opengl.jar;lib/processing-1.0.3-essentials/libraries/opengl/library/jogl.jar;lib/processing-1.0.3-essentials/libraries/opengl/library/gluegen-rt.jar"
java -Xmx512m -Djava.library.path=lib/processing-1.0.3-essentials/libraries/opengl/library peripheral.viz.VizStartupFrame
