/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SensorPanel.java
 *
 * Created on 27.05.2009, 14:20:47
 */

package peripheral.designer;

import peripheral.logic.DisplayConfiguration;
import peripheral.logic.sensor.SensorServer;
import peripheral.logic.sensor.XmlMetaParser;

/**
 *
 * @author Andi
 */
public class SensorPanel extends javax.swing.JPanel {

    /** Creates new form SensorPanel */
    public SensorPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        initTestSensorServerButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        initTestSensorServerButton.setText("Init TestSensorServer");
        initTestSensorServerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initTestSensorServerButtonActionPerformed(evt);
            }
        });
        add(initTestSensorServerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void initTestSensorServerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initTestSensorServerButtonActionPerformed
        // Create Server
        SensorServer server = new SensorServer("http://dyn167048.wlan.jku.at", "8080", "admin");

        // Get Server's XML Parser
        XmlMetaParser xml = server.getXmlMetaParser();
        xml.createInstancesFromXML();        // TODO add your handling code here:

        DisplayConfiguration.getInstance().getSensorServer().add(server);
    }//GEN-LAST:event_initTestSensorServerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton initTestSensorServerButton;
    // End of variables declaration//GEN-END:variables

}
